"""Variables prefixed with `DEFAULT` should be able to be overridden by
configuration file and command-line arguments."""

UNIT = 100000000        # The same across assets.


# Versions
VERSION_MAJOR = 9
VERSION_MINOR = 59
VERSION_REVISION = 4
VERSION_STRING = str(VERSION_MAJOR) + '.' + str(VERSION_MINOR) + '.' + str(VERSION_REVISION)

VERSION_FILE = 'https://counterpartyxcp.github.io/counterparty-lib/counterpartylib/protocol_changes.json'

# Counterparty protocol
TXTYPE_FORMAT = '>I'

TWO_WEEKS = 2 * 7 * 24 * 3600
MAX_EXPIRATION = 4 * 2016   # Two months

MEMPOOL_BLOCK_HASH = 'mempool'
MEMPOOL_BLOCK_INDEX = 9999999


# SQLite3
MAX_INT = 2**63 - 1


# Bitcoin Core
OP_RETURN_MAX_SIZE = 40 # bytes


# Currency agnosticism
BTC = 'DOGE'
XCP = 'XDP'

BTC_NAME = 'Dogecoin'
XCP_NAME = 'Dogeparty-coinwarp'
APP_NAME = XCP_NAME.lower()

DEFAULT_RPC_PORT_TESTNET = 15000
DEFAULT_RPC_PORT = 5000

DEFAULT_BACKEND_RPC_PORT_TESTNET = 44555
DEFAULT_BACKEND_RPC_PORT = 22555
DEFAULT_BACKEND_PORT_TESTNET = 44555
DEFAULT_BACKEND_PORT = 22555

UNSPENDABLE_TESTNET = 'ndogepartyxxxxxxxxxxxxxxxxxxwpsZCH'
UNSPENDABLE_MAINNET = 'DDogepartyxxxxxxxxxxxxxxxxxxw1dfzr'

ADDRESSVERSION_TESTNET = b'q'
# PRIVATEKEY_VERSION_TESTNET =
ADDRESSVERSION_MAINNET = b'\x1e'
PRIVATEKEY_VERSION_MAINNET = b'\x9e'
MAGIC_BYTES_TESTNET = b'\xfc\xc1\xb7\xdc'   # For bip-0010
MAGIC_BYTES_MAINNET = b'\xc0\xc0\xc0\xc0'   # For bip-0010

BLOCK_FIRST_TESTNET_TESTCOIN = 124678
BURN_START_TESTNET_TESTCOIN = BLOCK_FIRST_TESTNET_TESTCOIN
BURN_END_TESTNET_TESTCOIN = 26280000    # Fifty years, at 1 minute per block.

BLOCK_FIRST_TESTNET = BLOCK_FIRST_TESTNET_TESTCOIN
#BLOCK_FIRST_TESTNET_HASH = ''
BURN_START_TESTNET =  BURN_START_TESTNET_TESTCOIN
BURN_END_TESTNET = 26280000             # Fifty years, at 1 minute per block.

BLOCK_FIRST_MAINNET_TESTCOIN = 335642
BURN_START_MAINNET_TESTCOIN = BLOCK_FIRST_MAINNET_TESTCOIN
BURN_END_MAINNET_TESTCOIN = 26280000    # Fifty years, at 1 minute per block.

BLOCK_FIRST_MAINNET = BLOCK_FIRST_MAINNET_TESTCOIN
BLOCK_FIRST_MAINNET_HASH = 'd7d6f6bdd0c422defacf8544e6d4c96f8cbe249772872ec76de830dd99958f49'
BURN_START_MAINNET = BURN_START_MAINNET_TESTCOIN
BURN_END_MAINNET = BURN_START_MAINNET + 30*24*60    # 30 days burn period with 1 min target time per block.

# Protocol defaults

# NOTE: If the DUST_SIZE constants are changed, they MUST also be changed in counterblockd/dogepartylib/config.py as well
DEFAULT_REGULAR_DUST_SIZE = UNIT 		  # 1 DOGE; there is not dust limit in Dogecoin, but every txout < 1 DOGE, cost 1 DOGE in fee
DEFAULT_MULTISIG_DUST_SIZE = UNIT * 2 # 2 DOGE.
DEFAULT_OP_RETURN_VALUE = 0 			    # 0 DOGE.
DEFAULT_FEE_PER_KB = UNIT             # 1 DOGE.


# UI defaults
DEFAULT_FEE_FRACTION_REQUIRED = .009   # 0.90%
DEFAULT_FEE_FRACTION_PROVIDED = .01    # 1.00%

DEFAULT_REQUESTS_TIMEOUT = 20
DEFAULT_RPC_BATCH_SIZE = 20

# Custom exit codes
EXITCODE_UPDATE_REQUIRED = 5


DEFAULT_CHECK_ASSET_CONSERVATION = True
NAMED_ASSET_MAXLEN = 14

BACKEND_RAW_TRANSACTIONS_CACHE_SIZE = 20000
BACKEND_RPC_BATCH_NUM_WORKERS = 6

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
